// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXe_wmxt09AqH0lzPqOX-YdH4d4mbaQqQ',
    appId: '1:658541933794:web:a3b2fd7aada19a755f1abb',
    messagingSenderId: '658541933794',
    projectId: 'mj-mahasiswa',
    authDomain: 'mj-mahasiswa.firebaseapp.com',
    storageBucket: 'mj-mahasiswa.firebasestorage.app',
    measurementId: 'G-HMSC9LZ55Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZ7_aoPzlJouBgMLpTJ4RQO6wJ5hWW5A',
    appId: '1:658541933794:android:d2dc5bcbaeadc5985f1abb',
    messagingSenderId: '658541933794',
    projectId: 'mj-mahasiswa',
    storageBucket: 'mj-mahasiswa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tDG44tAYEbjKLoBQxS61FRJM5nd1tao',
    appId: '1:658541933794:ios:56b8c2feb5718c345f1abb',
    messagingSenderId: '658541933794',
    projectId: 'mj-mahasiswa',
    storageBucket: 'mj-mahasiswa.firebasestorage.app',
    iosClientId: '658541933794-j9lciorn2msgif34et8mbo9afsouvac2.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkMjMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8tDG44tAYEbjKLoBQxS61FRJM5nd1tao',
    appId: '1:658541933794:ios:56b8c2feb5718c345f1abb',
    messagingSenderId: '658541933794',
    projectId: 'mj-mahasiswa',
    storageBucket: 'mj-mahasiswa.firebasestorage.app',
    iosClientId: '658541933794-j9lciorn2msgif34et8mbo9afsouvac2.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkMjMahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXe_wmxt09AqH0lzPqOX-YdH4d4mbaQqQ',
    appId: '1:658541933794:web:63b55a9674750ad15f1abb',
    messagingSenderId: '658541933794',
    projectId: 'mj-mahasiswa',
    authDomain: 'mj-mahasiswa.firebaseapp.com',
    storageBucket: 'mj-mahasiswa.firebasestorage.app',
    measurementId: 'G-J6XET8CZTZ',
  );
}
